# Docs for all config options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"  # location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 21
      semver-minor-days: 14
      semver-patch-days: 7
    ignore:
      - dependency-name: "ruff"
        versions:
          - ">=0.13.0"
